// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7mTUk8cPJwkixICdfzCUL_VTrz0GFj98',
    appId: '1:872400097742:web:06cfe125b0886e16ed9b9f',
    messagingSenderId: '872400097742',
    projectId: 'travel-link-e401e',
    authDomain: 'travel-link-e401e.firebaseapp.com',
    storageBucket: 'travel-link-e401e.firebasestorage.app',
    measurementId: 'G-JL2C6EVQRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-p6XFA3sf6wNXqzQLFs55L2bsWkAmYto',
    appId: '1:872400097742:android:3d0328f589ff0325ed9b9f',
    messagingSenderId: '872400097742',
    projectId: 'travel-link-e401e',
    storageBucket: 'travel-link-e401e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFd1KRSh89iz3qjS_0OSGBSb0Occfu39M',
    appId: '1:872400097742:ios:9827dea434b02741ed9b9f',
    messagingSenderId: '872400097742',
    projectId: 'travel-link-e401e',
    storageBucket: 'travel-link-e401e.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7mTUk8cPJwkixICdfzCUL_VTrz0GFj98',
    appId: '1:872400097742:web:3b458c8d608903b1ed9b9f',
    messagingSenderId: '872400097742',
    projectId: 'travel-link-e401e',
    authDomain: 'travel-link-e401e.firebaseapp.com',
    storageBucket: 'travel-link-e401e.firebasestorage.app',
    measurementId: 'G-7JEGD6SRLV',
  );
}
